// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto

package test.grpc.grpc;

public interface XCmdResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc_package.XCmdResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>string result = 2;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 2;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>string encode = 3;</code>
   * @return The encode.
   */
  java.lang.String getEncode();
  /**
   * <code>string encode = 3;</code>
   * @return The bytes for encode.
   */
  com.google.protobuf.ByteString
      getEncodeBytes();

  /**
   * <code>string filter_result = 4;</code>
   * @return The filterResult.
   */
  java.lang.String getFilterResult();
  /**
   * <code>string filter_result = 4;</code>
   * @return The bytes for filterResult.
   */
  com.google.protobuf.ByteString
      getFilterResultBytes();
}
