// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto

package test.grpc.grpc;

public interface XFileCmdsByIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc_package.XFileCmdsByID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileid = 1;</code>
   * @return The fileid.
   */
  java.lang.String getFileid();
  /**
   * <code>string fileid = 1;</code>
   * @return The bytes for fileid.
   */
  com.google.protobuf.ByteString
      getFileidBytes();
}
