// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto

package test.grpc.grpc;

public interface XFileCmdsByContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc_package.XFileCmdsByContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string filecontent = 2;</code>
   * @return The filecontent.
   */
  java.lang.String getFilecontent();
  /**
   * <code>string filecontent = 2;</code>
   * @return The bytes for filecontent.
   */
  com.google.protobuf.ByteString
      getFilecontentBytes();

  /**
   * <code>string checksum = 3;</code>
   * @return The checksum.
   */
  java.lang.String getChecksum();
  /**
   * <code>string checksum = 3;</code>
   * @return The bytes for checksum.
   */
  com.google.protobuf.ByteString
      getChecksumBytes();
}
