// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto

package test.grpc.grpc;

public interface XFileCmdsByPathOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc_package.XFileCmdsByPath)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filepath = 1;</code>
   * @return The filepath.
   */
  java.lang.String getFilepath();
  /**
   * <code>string filepath = 1;</code>
   * @return The bytes for filepath.
   */
  com.google.protobuf.ByteString
      getFilepathBytes();
}
