// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto

package test.grpc.grpc;

public interface XRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rpc_package.XRequest)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1-100 for control
   * </pre>
   *
   * <code>.rpc_package.XRoute route = 1;</code>
   * @return Whether the route field is set.
   */
  boolean hasRoute();
  /**
   * <pre>
   * 1-100 for control
   * </pre>
   *
   * <code>.rpc_package.XRoute route = 1;</code>
   * @return The route.
   */
  test.grpc.grpc.XRoute getRoute();
  /**
   * <pre>
   * 1-100 for control
   * </pre>
   *
   * <code>.rpc_package.XRoute route = 1;</code>
   */
  test.grpc.grpc.XRouteOrBuilder getRouteOrBuilder();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
  getUsernameBytes();

  /**
   * <code>string usermima = 3;</code>
   * @return The usermima.
   */
  java.lang.String getUsermima();
  /**
   * <code>string usermima = 3;</code>
   * @return The bytes for usermima.
   */
  com.google.protobuf.ByteString
  getUsermimaBytes();

  /**
   * <code>int32 serviceid = 4;</code>
   * @return The serviceid.
   */
  int getServiceid();

  /**
   * <code>int32 type = 5;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>string token = 6;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 6;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
  getTokenBytes();

  /**
   * <code>string client = 8;</code>
   * @return The client.
   */
  java.lang.String getClient();
  /**
   * <code>string client = 8;</code>
   * @return The bytes for client.
   */
  com.google.protobuf.ByteString
  getClientBytes();

  /**
   * <code>int32 warnflag = 9;</code>
   * @return The warnflag.
   */
  int getWarnflag();

  /**
   * <code>string appcoding = 10;</code>
   * @return The appcoding.
   */
  java.lang.String getAppcoding();
  /**
   * <code>string appcoding = 10;</code>
   * @return The bytes for appcoding.
   */
  com.google.protobuf.ByteString
  getAppcodingBytes();

  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  java.util.List<test.grpc.grpc.XCmd>
  getCommandsList();
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  test.grpc.grpc.XCmd getCommands(int index);
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  int getCommandsCount();
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  java.util.List<? extends test.grpc.grpc.XCmdOrBuilder>
  getCommandsOrBuilderList();
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  test.grpc.grpc.XCmdOrBuilder getCommandsOrBuilder(
          int index);

  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  java.util.List<test.grpc.grpc.XCmd>
  getExtdcommandsList();
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  test.grpc.grpc.XCmd getExtdcommands(int index);
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  int getExtdcommandsCount();
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  java.util.List<? extends test.grpc.grpc.XCmdOrBuilder>
  getExtdcommandsOrBuilderList();
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  test.grpc.grpc.XCmdOrBuilder getExtdcommandsOrBuilder(
          int index);

  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  java.util.List<test.grpc.grpc.XFileCmd>
  getFilecommandsList();
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  test.grpc.grpc.XFileCmd getFilecommands(int index);
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  int getFilecommandsCount();
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  java.util.List<? extends test.grpc.grpc.XFileCmdOrBuilder>
  getFilecommandsOrBuilderList();
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  test.grpc.grpc.XFileCmdOrBuilder getFilecommandsOrBuilder(
          int index);
}
