// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto


package test.grpc.grpc;

/**
 * Protobuf type {@code rpc_package.XRequest}
 */
public final class XRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:rpc_package.XRequest)
        XRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use XRequest.newBuilder() to construct.
  private XRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private XRequest() {
    username_ = "";
    usermima_ = "";
    token_ = "";
    client_ = "";
    appcoding_ = "";
    commands_ = java.util.Collections.emptyList();
    extdcommands_ = java.util.Collections.emptyList();
    filecommands_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
    return new XRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private XRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            test.grpc.grpc.XRoute.Builder subBuilder = null;
            if (route_ != null) {
              subBuilder = route_.toBuilder();
            }
            route_ = input.readMessage(test.grpc.grpc.XRoute.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(route_);
              route_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            usermima_ = s;
            break;
          }
          case 32: {

            serviceid_ = input.readInt32();
            break;
          }
          case 40: {

            type_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            client_ = s;
            break;
          }
          case 72: {

            warnflag_ = input.readInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            appcoding_ = s;
            break;
          }
          case 810: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              commands_ = new java.util.ArrayList<test.grpc.grpc.XCmd>();
              mutable_bitField0_ |= 0x00000001;
            }
            commands_.add(
                    input.readMessage(test.grpc.grpc.XCmd.parser(), extensionRegistry));
            break;
          }
          case 818: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              extdcommands_ = new java.util.ArrayList<test.grpc.grpc.XCmd>();
              mutable_bitField0_ |= 0x00000002;
            }
            extdcommands_.add(
                    input.readMessage(test.grpc.grpc.XCmd.parser(), extensionRegistry));
            break;
          }
          case 826: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              filecommands_ = new java.util.ArrayList<test.grpc.grpc.XFileCmd>();
              mutable_bitField0_ |= 0x00000004;
            }
            filecommands_.add(
                    input.readMessage(test.grpc.grpc.XFileCmd.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        commands_ = java.util.Collections.unmodifiableList(commands_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        extdcommands_ = java.util.Collections.unmodifiableList(extdcommands_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        filecommands_ = java.util.Collections.unmodifiableList(filecommands_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    test.grpc.grpc.XRequest.class, test.grpc.grpc.XRequest.Builder.class);
  }

  public static final int ROUTE_FIELD_NUMBER = 1;
  private test.grpc.grpc.XRoute route_;
  /**
   * <pre>
   * 1-100 for control
   * </pre>
   *
   * <code>.rpc_package.XRoute route = 1;</code>
   * @return Whether the route field is set.
   */
  @java.lang.Override
  public boolean hasRoute() {
    return route_ != null;
  }
  /**
   * <pre>
   * 1-100 for control
   * </pre>
   *
   * <code>.rpc_package.XRoute route = 1;</code>
   * @return The route.
   */
  @java.lang.Override
  public test.grpc.grpc.XRoute getRoute() {
    return route_ == null ? test.grpc.grpc.XRoute.getDefaultInstance() : route_;
  }
  /**
   * <pre>
   * 1-100 for control
   * </pre>
   *
   * <code>.rpc_package.XRoute route = 1;</code>
   */
  @java.lang.Override
  public test.grpc.grpc.XRouteOrBuilder getRouteOrBuilder() {
    return getRoute();
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERMIMA_FIELD_NUMBER = 3;
  private volatile java.lang.Object usermima_;
  /**
   * <code>string usermima = 3;</code>
   * @return The usermima.
   */
  @java.lang.Override
  public java.lang.String getUsermima() {
    java.lang.Object ref = usermima_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      usermima_ = s;
      return s;
    }
  }
  /**
   * <code>string usermima = 3;</code>
   * @return The bytes for usermima.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getUsermimaBytes() {
    java.lang.Object ref = usermima_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      usermima_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICEID_FIELD_NUMBER = 4;
  private int serviceid_;
  /**
   * <code>int32 serviceid = 4;</code>
   * @return The serviceid.
   */
  @java.lang.Override
  public int getServiceid() {
    return serviceid_;
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private int type_;
  /**
   * <code>int32 type = 5;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int TOKEN_FIELD_NUMBER = 6;
  private volatile java.lang.Object token_;
  /**
   * <code>string token = 6;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>string token = 6;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_FIELD_NUMBER = 8;
  private volatile java.lang.Object client_;
  /**
   * <code>string client = 8;</code>
   * @return The client.
   */
  @java.lang.Override
  public java.lang.String getClient() {
    java.lang.Object ref = client_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      client_ = s;
      return s;
    }
  }
  /**
   * <code>string client = 8;</code>
   * @return The bytes for client.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getClientBytes() {
    java.lang.Object ref = client_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      client_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WARNFLAG_FIELD_NUMBER = 9;
  private int warnflag_;
  /**
   * <code>int32 warnflag = 9;</code>
   * @return The warnflag.
   */
  @java.lang.Override
  public int getWarnflag() {
    return warnflag_;
  }

  public static final int APPCODING_FIELD_NUMBER = 10;
  private volatile java.lang.Object appcoding_;
  /**
   * <code>string appcoding = 10;</code>
   * @return The appcoding.
   */
  @java.lang.Override
  public java.lang.String getAppcoding() {
    java.lang.Object ref = appcoding_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appcoding_ = s;
      return s;
    }
  }
  /**
   * <code>string appcoding = 10;</code>
   * @return The bytes for appcoding.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getAppcodingBytes() {
    java.lang.Object ref = appcoding_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      appcoding_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMANDS_FIELD_NUMBER = 101;
  private java.util.List<test.grpc.grpc.XCmd> commands_;
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  @java.lang.Override
  public java.util.List<test.grpc.grpc.XCmd> getCommandsList() {
    return commands_;
  }
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  @java.lang.Override
  public java.util.List<? extends test.grpc.grpc.XCmdOrBuilder>
  getCommandsOrBuilderList() {
    return commands_;
  }
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  @java.lang.Override
  public int getCommandsCount() {
    return commands_.size();
  }
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  @java.lang.Override
  public test.grpc.grpc.XCmd getCommands(int index) {
    return commands_.get(index);
  }
  /**
   * <pre>
   * 101 - 200, for command
   * </pre>
   *
   * <code>repeated .rpc_package.XCmd commands = 101;</code>
   */
  @java.lang.Override
  public test.grpc.grpc.XCmdOrBuilder getCommandsOrBuilder(
          int index) {
    return commands_.get(index);
  }

  public static final int EXTDCOMMANDS_FIELD_NUMBER = 102;
  private java.util.List<test.grpc.grpc.XCmd> extdcommands_;
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  @java.lang.Override
  public java.util.List<test.grpc.grpc.XCmd> getExtdcommandsList() {
    return extdcommands_;
  }
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  @java.lang.Override
  public java.util.List<? extends test.grpc.grpc.XCmdOrBuilder>
  getExtdcommandsOrBuilderList() {
    return extdcommands_;
  }
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  @java.lang.Override
  public int getExtdcommandsCount() {
    return extdcommands_.size();
  }
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  @java.lang.Override
  public test.grpc.grpc.XCmd getExtdcommands(int index) {
    return extdcommands_.get(index);
  }
  /**
   * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
   */
  @java.lang.Override
  public test.grpc.grpc.XCmdOrBuilder getExtdcommandsOrBuilder(
          int index) {
    return extdcommands_.get(index);
  }

  public static final int FILECOMMANDS_FIELD_NUMBER = 103;
  private java.util.List<test.grpc.grpc.XFileCmd> filecommands_;
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  @java.lang.Override
  public java.util.List<test.grpc.grpc.XFileCmd> getFilecommandsList() {
    return filecommands_;
  }
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  @java.lang.Override
  public java.util.List<? extends test.grpc.grpc.XFileCmdOrBuilder>
  getFilecommandsOrBuilderList() {
    return filecommands_;
  }
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  @java.lang.Override
  public int getFilecommandsCount() {
    return filecommands_.size();
  }
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  @java.lang.Override
  public test.grpc.grpc.XFileCmd getFilecommands(int index) {
    return filecommands_.get(index);
  }
  /**
   * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
   */
  @java.lang.Override
  public test.grpc.grpc.XFileCmdOrBuilder getFilecommandsOrBuilder(
          int index) {
    return filecommands_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (route_ != null) {
      output.writeMessage(1, getRoute());
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!getUsermimaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, usermima_);
    }
    if (serviceid_ != 0) {
      output.writeInt32(4, serviceid_);
    }
    if (type_ != 0) {
      output.writeInt32(5, type_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, token_);
    }
    if (!getClientBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, client_);
    }
    if (warnflag_ != 0) {
      output.writeInt32(9, warnflag_);
    }
    if (!getAppcodingBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, appcoding_);
    }
    for (int i = 0; i < commands_.size(); i++) {
      output.writeMessage(101, commands_.get(i));
    }
    for (int i = 0; i < extdcommands_.size(); i++) {
      output.writeMessage(102, extdcommands_.get(i));
    }
    for (int i = 0; i < filecommands_.size(); i++) {
      output.writeMessage(103, filecommands_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (route_ != null) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, getRoute());
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!getUsermimaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, usermima_);
    }
    if (serviceid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(4, serviceid_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(5, type_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, token_);
    }
    if (!getClientBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, client_);
    }
    if (warnflag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(9, warnflag_);
    }
    if (!getAppcodingBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, appcoding_);
    }
    for (int i = 0; i < commands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(101, commands_.get(i));
    }
    for (int i = 0; i < extdcommands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(102, extdcommands_.get(i));
    }
    for (int i = 0; i < filecommands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(103, filecommands_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof test.grpc.grpc.XRequest)) {
      return super.equals(obj);
    }
    test.grpc.grpc.XRequest other = (test.grpc.grpc.XRequest) obj;

    if (hasRoute() != other.hasRoute()) return false;
    if (hasRoute()) {
      if (!getRoute()
              .equals(other.getRoute())) return false;
    }
    if (!getUsername()
            .equals(other.getUsername())) return false;
    if (!getUsermima()
            .equals(other.getUsermima())) return false;
    if (getServiceid()
            != other.getServiceid()) return false;
    if (getType()
            != other.getType()) return false;
    if (!getToken()
            .equals(other.getToken())) return false;
    if (!getClient()
            .equals(other.getClient())) return false;
    if (getWarnflag()
            != other.getWarnflag()) return false;
    if (!getAppcoding()
            .equals(other.getAppcoding())) return false;
    if (!getCommandsList()
            .equals(other.getCommandsList())) return false;
    if (!getExtdcommandsList()
            .equals(other.getExtdcommandsList())) return false;
    if (!getFilecommandsList()
            .equals(other.getFilecommandsList())) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRoute()) {
      hash = (37 * hash) + ROUTE_FIELD_NUMBER;
      hash = (53 * hash) + getRoute().hashCode();
    }
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + USERMIMA_FIELD_NUMBER;
    hash = (53 * hash) + getUsermima().hashCode();
    hash = (37 * hash) + SERVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getServiceid();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + CLIENT_FIELD_NUMBER;
    hash = (53 * hash) + getClient().hashCode();
    hash = (37 * hash) + WARNFLAG_FIELD_NUMBER;
    hash = (53 * hash) + getWarnflag();
    hash = (37 * hash) + APPCODING_FIELD_NUMBER;
    hash = (53 * hash) + getAppcoding().hashCode();
    if (getCommandsCount() > 0) {
      hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getCommandsList().hashCode();
    }
    if (getExtdcommandsCount() > 0) {
      hash = (37 * hash) + EXTDCOMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getExtdcommandsList().hashCode();
    }
    if (getFilecommandsCount() > 0) {
      hash = (37 * hash) + FILECOMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getFilecommandsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static test.grpc.grpc.XRequest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.grpc.grpc.XRequest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.grpc.grpc.XRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.grpc.grpc.XRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.grpc.grpc.XRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.grpc.grpc.XRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.grpc.grpc.XRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static test.grpc.grpc.XRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static test.grpc.grpc.XRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }
  public static test.grpc.grpc.XRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static test.grpc.grpc.XRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static test.grpc.grpc.XRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(test.grpc.grpc.XRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc_package.XRequest}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:rpc_package.XRequest)
          test.grpc.grpc.XRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      test.grpc.grpc.XRequest.class, test.grpc.grpc.XRequest.Builder.class);
    }

    // Construct using test.grpc.grpc.XRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommandsFieldBuilder();
        getExtdcommandsFieldBuilder();
        getFilecommandsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (routeBuilder_ == null) {
        route_ = null;
      } else {
        route_ = null;
        routeBuilder_ = null;
      }
      username_ = "";

      usermima_ = "";

      serviceid_ = 0;

      type_ = 0;

      token_ = "";

      client_ = "";

      warnflag_ = 0;

      appcoding_ = "";

      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        commandsBuilder_.clear();
      }
      if (extdcommandsBuilder_ == null) {
        extdcommands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        extdcommandsBuilder_.clear();
      }
      if (filecommandsBuilder_ == null) {
        filecommands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        filecommandsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRequest_descriptor;
    }

    @java.lang.Override
    public test.grpc.grpc.XRequest getDefaultInstanceForType() {
      return test.grpc.grpc.XRequest.getDefaultInstance();
    }

    @java.lang.Override
    public test.grpc.grpc.XRequest build() {
      test.grpc.grpc.XRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public test.grpc.grpc.XRequest buildPartial() {
      test.grpc.grpc.XRequest result = new test.grpc.grpc.XRequest(this);
      int from_bitField0_ = bitField0_;
      if (routeBuilder_ == null) {
        result.route_ = route_;
      } else {
        result.route_ = routeBuilder_.build();
      }
      result.username_ = username_;
      result.usermima_ = usermima_;
      result.serviceid_ = serviceid_;
      result.type_ = type_;
      result.token_ = token_;
      result.client_ = client_;
      result.warnflag_ = warnflag_;
      result.appcoding_ = appcoding_;
      if (commandsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          commands_ = java.util.Collections.unmodifiableList(commands_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.commands_ = commands_;
      } else {
        result.commands_ = commandsBuilder_.build();
      }
      if (extdcommandsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          extdcommands_ = java.util.Collections.unmodifiableList(extdcommands_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.extdcommands_ = extdcommands_;
      } else {
        result.extdcommands_ = extdcommandsBuilder_.build();
      }
      if (filecommandsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          filecommands_ = java.util.Collections.unmodifiableList(filecommands_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.filecommands_ = filecommands_;
      } else {
        result.filecommands_ = filecommandsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof test.grpc.grpc.XRequest) {
        return mergeFrom((test.grpc.grpc.XRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(test.grpc.grpc.XRequest other) {
      if (other == test.grpc.grpc.XRequest.getDefaultInstance()) return this;
      if (other.hasRoute()) {
        mergeRoute(other.getRoute());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getUsermima().isEmpty()) {
        usermima_ = other.usermima_;
        onChanged();
      }
      if (other.getServiceid() != 0) {
        setServiceid(other.getServiceid());
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (!other.getClient().isEmpty()) {
        client_ = other.client_;
        onChanged();
      }
      if (other.getWarnflag() != 0) {
        setWarnflag(other.getWarnflag());
      }
      if (!other.getAppcoding().isEmpty()) {
        appcoding_ = other.appcoding_;
        onChanged();
      }
      if (commandsBuilder_ == null) {
        if (!other.commands_.isEmpty()) {
          if (commands_.isEmpty()) {
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCommandsIsMutable();
            commands_.addAll(other.commands_);
          }
          onChanged();
        }
      } else {
        if (!other.commands_.isEmpty()) {
          if (commandsBuilder_.isEmpty()) {
            commandsBuilder_.dispose();
            commandsBuilder_ = null;
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000001);
            commandsBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getCommandsFieldBuilder() : null;
          } else {
            commandsBuilder_.addAllMessages(other.commands_);
          }
        }
      }
      if (extdcommandsBuilder_ == null) {
        if (!other.extdcommands_.isEmpty()) {
          if (extdcommands_.isEmpty()) {
            extdcommands_ = other.extdcommands_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureExtdcommandsIsMutable();
            extdcommands_.addAll(other.extdcommands_);
          }
          onChanged();
        }
      } else {
        if (!other.extdcommands_.isEmpty()) {
          if (extdcommandsBuilder_.isEmpty()) {
            extdcommandsBuilder_.dispose();
            extdcommandsBuilder_ = null;
            extdcommands_ = other.extdcommands_;
            bitField0_ = (bitField0_ & ~0x00000002);
            extdcommandsBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getExtdcommandsFieldBuilder() : null;
          } else {
            extdcommandsBuilder_.addAllMessages(other.extdcommands_);
          }
        }
      }
      if (filecommandsBuilder_ == null) {
        if (!other.filecommands_.isEmpty()) {
          if (filecommands_.isEmpty()) {
            filecommands_ = other.filecommands_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFilecommandsIsMutable();
            filecommands_.addAll(other.filecommands_);
          }
          onChanged();
        }
      } else {
        if (!other.filecommands_.isEmpty()) {
          if (filecommandsBuilder_.isEmpty()) {
            filecommandsBuilder_.dispose();
            filecommandsBuilder_ = null;
            filecommands_ = other.filecommands_;
            bitField0_ = (bitField0_ & ~0x00000004);
            filecommandsBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getFilecommandsFieldBuilder() : null;
          } else {
            filecommandsBuilder_.addAllMessages(other.filecommands_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      test.grpc.grpc.XRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (test.grpc.grpc.XRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private test.grpc.grpc.XRoute route_;
    private com.google.protobuf.SingleFieldBuilderV3<
            test.grpc.grpc.XRoute, test.grpc.grpc.XRoute.Builder, test.grpc.grpc.XRouteOrBuilder> routeBuilder_;
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     * @return Whether the route field is set.
     */
    public boolean hasRoute() {
      return routeBuilder_ != null || route_ != null;
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     * @return The route.
     */
    public test.grpc.grpc.XRoute getRoute() {
      if (routeBuilder_ == null) {
        return route_ == null ? test.grpc.grpc.XRoute.getDefaultInstance() : route_;
      } else {
        return routeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     */
    public Builder setRoute(test.grpc.grpc.XRoute value) {
      if (routeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        route_ = value;
        onChanged();
      } else {
        routeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     */
    public Builder setRoute(
            test.grpc.grpc.XRoute.Builder builderForValue) {
      if (routeBuilder_ == null) {
        route_ = builderForValue.build();
        onChanged();
      } else {
        routeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     */
    public Builder mergeRoute(test.grpc.grpc.XRoute value) {
      if (routeBuilder_ == null) {
        if (route_ != null) {
          route_ =
                  test.grpc.grpc.XRoute.newBuilder(route_).mergeFrom(value).buildPartial();
        } else {
          route_ = value;
        }
        onChanged();
      } else {
        routeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     */
    public Builder clearRoute() {
      if (routeBuilder_ == null) {
        route_ = null;
        onChanged();
      } else {
        route_ = null;
        routeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     */
    public test.grpc.grpc.XRoute.Builder getRouteBuilder() {

      onChanged();
      return getRouteFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     */
    public test.grpc.grpc.XRouteOrBuilder getRouteOrBuilder() {
      if (routeBuilder_ != null) {
        return routeBuilder_.getMessageOrBuilder();
      } else {
        return route_ == null ?
                test.grpc.grpc.XRoute.getDefaultInstance() : route_;
      }
    }
    /**
     * <pre>
     * 1-100 for control
     * </pre>
     *
     * <code>.rpc_package.XRoute route = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            test.grpc.grpc.XRoute, test.grpc.grpc.XRoute.Builder, test.grpc.grpc.XRouteOrBuilder>
    getRouteFieldBuilder() {
      if (routeBuilder_ == null) {
        routeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                test.grpc.grpc.XRoute, test.grpc.grpc.XRoute.Builder, test.grpc.grpc.XRouteOrBuilder>(
                getRoute(),
                getParentForChildren(),
                isClean());
        route_ = null;
      }
      return routeBuilder_;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
    getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {

      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object usermima_ = "";
    /**
     * <code>string usermima = 3;</code>
     * @return The usermima.
     */
    public java.lang.String getUsermima() {
      java.lang.Object ref = usermima_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usermima_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string usermima = 3;</code>
     * @return The bytes for usermima.
     */
    public com.google.protobuf.ByteString
    getUsermimaBytes() {
      java.lang.Object ref = usermima_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        usermima_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string usermima = 3;</code>
     * @param value The usermima to set.
     * @return This builder for chaining.
     */
    public Builder setUsermima(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      usermima_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string usermima = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsermima() {

      usermima_ = getDefaultInstance().getUsermima();
      onChanged();
      return this;
    }
    /**
     * <code>string usermima = 3;</code>
     * @param value The bytes for usermima to set.
     * @return This builder for chaining.
     */
    public Builder setUsermimaBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      usermima_ = value;
      onChanged();
      return this;
    }

    private int serviceid_ ;
    /**
     * <code>int32 serviceid = 4;</code>
     * @return The serviceid.
     */
    @java.lang.Override
    public int getServiceid() {
      return serviceid_;
    }
    /**
     * <code>int32 serviceid = 4;</code>
     * @param value The serviceid to set.
     * @return This builder for chaining.
     */
    public Builder setServiceid(int value) {

      serviceid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 serviceid = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceid() {

      serviceid_ = 0;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>int32 type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>int32 type = 5;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {

      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {

      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>string token = 6;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string token = 6;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
    getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string token = 6;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string token = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {

      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <code>string token = 6;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      token_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object client_ = "";
    /**
     * <code>string client = 8;</code>
     * @return The client.
     */
    public java.lang.String getClient() {
      java.lang.Object ref = client_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        client_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client = 8;</code>
     * @return The bytes for client.
     */
    public com.google.protobuf.ByteString
    getClientBytes() {
      java.lang.Object ref = client_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        client_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client = 8;</code>
     * @param value The client to set.
     * @return This builder for chaining.
     */
    public Builder setClient(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      client_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearClient() {

      client_ = getDefaultInstance().getClient();
      onChanged();
      return this;
    }
    /**
     * <code>string client = 8;</code>
     * @param value The bytes for client to set.
     * @return This builder for chaining.
     */
    public Builder setClientBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      client_ = value;
      onChanged();
      return this;
    }

    private int warnflag_ ;
    /**
     * <code>int32 warnflag = 9;</code>
     * @return The warnflag.
     */
    @java.lang.Override
    public int getWarnflag() {
      return warnflag_;
    }
    /**
     * <code>int32 warnflag = 9;</code>
     * @param value The warnflag to set.
     * @return This builder for chaining.
     */
    public Builder setWarnflag(int value) {

      warnflag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 warnflag = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearWarnflag() {

      warnflag_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object appcoding_ = "";
    /**
     * <code>string appcoding = 10;</code>
     * @return The appcoding.
     */
    public java.lang.String getAppcoding() {
      java.lang.Object ref = appcoding_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appcoding_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appcoding = 10;</code>
     * @return The bytes for appcoding.
     */
    public com.google.protobuf.ByteString
    getAppcodingBytes() {
      java.lang.Object ref = appcoding_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        appcoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appcoding = 10;</code>
     * @param value The appcoding to set.
     * @return This builder for chaining.
     */
    public Builder setAppcoding(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      appcoding_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string appcoding = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppcoding() {

      appcoding_ = getDefaultInstance().getAppcoding();
      onChanged();
      return this;
    }
    /**
     * <code>string appcoding = 10;</code>
     * @param value The bytes for appcoding to set.
     * @return This builder for chaining.
     */
    public Builder setAppcodingBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      appcoding_ = value;
      onChanged();
      return this;
    }

    private java.util.List<test.grpc.grpc.XCmd> commands_ =
            java.util.Collections.emptyList();
    private void ensureCommandsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        commands_ = new java.util.ArrayList<test.grpc.grpc.XCmd>(commands_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            test.grpc.grpc.XCmd, test.grpc.grpc.XCmd.Builder, test.grpc.grpc.XCmdOrBuilder> commandsBuilder_;

    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public java.util.List<test.grpc.grpc.XCmd> getCommandsList() {
      if (commandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(commands_);
      } else {
        return commandsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public int getCommandsCount() {
      if (commandsBuilder_ == null) {
        return commands_.size();
      } else {
        return commandsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public test.grpc.grpc.XCmd getCommands(int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);
      } else {
        return commandsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder setCommands(
            int index, test.grpc.grpc.XCmd value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.set(index, value);
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder setCommands(
            int index, test.grpc.grpc.XCmd.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.set(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder addCommands(test.grpc.grpc.XCmd value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder addCommands(
            int index, test.grpc.grpc.XCmd value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(index, value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder addCommands(
            test.grpc.grpc.XCmd.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder addCommands(
            int index, test.grpc.grpc.XCmd.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder addAllCommands(
            java.lang.Iterable<? extends test.grpc.grpc.XCmd> values) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, commands_);
        onChanged();
      } else {
        commandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder clearCommands() {
      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        commandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public Builder removeCommands(int index) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.remove(index);
        onChanged();
      } else {
        commandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public test.grpc.grpc.XCmd.Builder getCommandsBuilder(
            int index) {
      return getCommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public test.grpc.grpc.XCmdOrBuilder getCommandsOrBuilder(
            int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);  } else {
        return commandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public java.util.List<? extends test.grpc.grpc.XCmdOrBuilder>
    getCommandsOrBuilderList() {
      if (commandsBuilder_ != null) {
        return commandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(commands_);
      }
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public test.grpc.grpc.XCmd.Builder addCommandsBuilder() {
      return getCommandsFieldBuilder().addBuilder(
              test.grpc.grpc.XCmd.getDefaultInstance());
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public test.grpc.grpc.XCmd.Builder addCommandsBuilder(
            int index) {
      return getCommandsFieldBuilder().addBuilder(
              index, test.grpc.grpc.XCmd.getDefaultInstance());
    }
    /**
     * <pre>
     * 101 - 200, for command
     * </pre>
     *
     * <code>repeated .rpc_package.XCmd commands = 101;</code>
     */
    public java.util.List<test.grpc.grpc.XCmd.Builder>
    getCommandsBuilderList() {
      return getCommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            test.grpc.grpc.XCmd, test.grpc.grpc.XCmd.Builder, test.grpc.grpc.XCmdOrBuilder>
    getCommandsFieldBuilder() {
      if (commandsBuilder_ == null) {
        commandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                test.grpc.grpc.XCmd, test.grpc.grpc.XCmd.Builder, test.grpc.grpc.XCmdOrBuilder>(
                commands_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        commands_ = null;
      }
      return commandsBuilder_;
    }

    private java.util.List<test.grpc.grpc.XCmd> extdcommands_ =
            java.util.Collections.emptyList();
    private void ensureExtdcommandsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        extdcommands_ = new java.util.ArrayList<test.grpc.grpc.XCmd>(extdcommands_);
        bitField0_ |= 0x00000002;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            test.grpc.grpc.XCmd, test.grpc.grpc.XCmd.Builder, test.grpc.grpc.XCmdOrBuilder> extdcommandsBuilder_;

    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public java.util.List<test.grpc.grpc.XCmd> getExtdcommandsList() {
      if (extdcommandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extdcommands_);
      } else {
        return extdcommandsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public int getExtdcommandsCount() {
      if (extdcommandsBuilder_ == null) {
        return extdcommands_.size();
      } else {
        return extdcommandsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public test.grpc.grpc.XCmd getExtdcommands(int index) {
      if (extdcommandsBuilder_ == null) {
        return extdcommands_.get(index);
      } else {
        return extdcommandsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder setExtdcommands(
            int index, test.grpc.grpc.XCmd value) {
      if (extdcommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtdcommandsIsMutable();
        extdcommands_.set(index, value);
        onChanged();
      } else {
        extdcommandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder setExtdcommands(
            int index, test.grpc.grpc.XCmd.Builder builderForValue) {
      if (extdcommandsBuilder_ == null) {
        ensureExtdcommandsIsMutable();
        extdcommands_.set(index, builderForValue.build());
        onChanged();
      } else {
        extdcommandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder addExtdcommands(test.grpc.grpc.XCmd value) {
      if (extdcommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtdcommandsIsMutable();
        extdcommands_.add(value);
        onChanged();
      } else {
        extdcommandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder addExtdcommands(
            int index, test.grpc.grpc.XCmd value) {
      if (extdcommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtdcommandsIsMutable();
        extdcommands_.add(index, value);
        onChanged();
      } else {
        extdcommandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder addExtdcommands(
            test.grpc.grpc.XCmd.Builder builderForValue) {
      if (extdcommandsBuilder_ == null) {
        ensureExtdcommandsIsMutable();
        extdcommands_.add(builderForValue.build());
        onChanged();
      } else {
        extdcommandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder addExtdcommands(
            int index, test.grpc.grpc.XCmd.Builder builderForValue) {
      if (extdcommandsBuilder_ == null) {
        ensureExtdcommandsIsMutable();
        extdcommands_.add(index, builderForValue.build());
        onChanged();
      } else {
        extdcommandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder addAllExtdcommands(
            java.lang.Iterable<? extends test.grpc.grpc.XCmd> values) {
      if (extdcommandsBuilder_ == null) {
        ensureExtdcommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, extdcommands_);
        onChanged();
      } else {
        extdcommandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder clearExtdcommands() {
      if (extdcommandsBuilder_ == null) {
        extdcommands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        extdcommandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public Builder removeExtdcommands(int index) {
      if (extdcommandsBuilder_ == null) {
        ensureExtdcommandsIsMutable();
        extdcommands_.remove(index);
        onChanged();
      } else {
        extdcommandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public test.grpc.grpc.XCmd.Builder getExtdcommandsBuilder(
            int index) {
      return getExtdcommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public test.grpc.grpc.XCmdOrBuilder getExtdcommandsOrBuilder(
            int index) {
      if (extdcommandsBuilder_ == null) {
        return extdcommands_.get(index);  } else {
        return extdcommandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public java.util.List<? extends test.grpc.grpc.XCmdOrBuilder>
    getExtdcommandsOrBuilderList() {
      if (extdcommandsBuilder_ != null) {
        return extdcommandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extdcommands_);
      }
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public test.grpc.grpc.XCmd.Builder addExtdcommandsBuilder() {
      return getExtdcommandsFieldBuilder().addBuilder(
              test.grpc.grpc.XCmd.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public test.grpc.grpc.XCmd.Builder addExtdcommandsBuilder(
            int index) {
      return getExtdcommandsFieldBuilder().addBuilder(
              index, test.grpc.grpc.XCmd.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc_package.XCmd extdcommands = 102;</code>
     */
    public java.util.List<test.grpc.grpc.XCmd.Builder>
    getExtdcommandsBuilderList() {
      return getExtdcommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            test.grpc.grpc.XCmd, test.grpc.grpc.XCmd.Builder, test.grpc.grpc.XCmdOrBuilder>
    getExtdcommandsFieldBuilder() {
      if (extdcommandsBuilder_ == null) {
        extdcommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                test.grpc.grpc.XCmd, test.grpc.grpc.XCmd.Builder, test.grpc.grpc.XCmdOrBuilder>(
                extdcommands_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        extdcommands_ = null;
      }
      return extdcommandsBuilder_;
    }

    private java.util.List<test.grpc.grpc.XFileCmd> filecommands_ =
            java.util.Collections.emptyList();
    private void ensureFilecommandsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        filecommands_ = new java.util.ArrayList<test.grpc.grpc.XFileCmd>(filecommands_);
        bitField0_ |= 0x00000004;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            test.grpc.grpc.XFileCmd, test.grpc.grpc.XFileCmd.Builder, test.grpc.grpc.XFileCmdOrBuilder> filecommandsBuilder_;

    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public java.util.List<test.grpc.grpc.XFileCmd> getFilecommandsList() {
      if (filecommandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(filecommands_);
      } else {
        return filecommandsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public int getFilecommandsCount() {
      if (filecommandsBuilder_ == null) {
        return filecommands_.size();
      } else {
        return filecommandsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public test.grpc.grpc.XFileCmd getFilecommands(int index) {
      if (filecommandsBuilder_ == null) {
        return filecommands_.get(index);
      } else {
        return filecommandsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder setFilecommands(
            int index, test.grpc.grpc.XFileCmd value) {
      if (filecommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilecommandsIsMutable();
        filecommands_.set(index, value);
        onChanged();
      } else {
        filecommandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder setFilecommands(
            int index, test.grpc.grpc.XFileCmd.Builder builderForValue) {
      if (filecommandsBuilder_ == null) {
        ensureFilecommandsIsMutable();
        filecommands_.set(index, builderForValue.build());
        onChanged();
      } else {
        filecommandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder addFilecommands(test.grpc.grpc.XFileCmd value) {
      if (filecommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilecommandsIsMutable();
        filecommands_.add(value);
        onChanged();
      } else {
        filecommandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder addFilecommands(
            int index, test.grpc.grpc.XFileCmd value) {
      if (filecommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilecommandsIsMutable();
        filecommands_.add(index, value);
        onChanged();
      } else {
        filecommandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder addFilecommands(
            test.grpc.grpc.XFileCmd.Builder builderForValue) {
      if (filecommandsBuilder_ == null) {
        ensureFilecommandsIsMutable();
        filecommands_.add(builderForValue.build());
        onChanged();
      } else {
        filecommandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder addFilecommands(
            int index, test.grpc.grpc.XFileCmd.Builder builderForValue) {
      if (filecommandsBuilder_ == null) {
        ensureFilecommandsIsMutable();
        filecommands_.add(index, builderForValue.build());
        onChanged();
      } else {
        filecommandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder addAllFilecommands(
            java.lang.Iterable<? extends test.grpc.grpc.XFileCmd> values) {
      if (filecommandsBuilder_ == null) {
        ensureFilecommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, filecommands_);
        onChanged();
      } else {
        filecommandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder clearFilecommands() {
      if (filecommandsBuilder_ == null) {
        filecommands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        filecommandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public Builder removeFilecommands(int index) {
      if (filecommandsBuilder_ == null) {
        ensureFilecommandsIsMutable();
        filecommands_.remove(index);
        onChanged();
      } else {
        filecommandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public test.grpc.grpc.XFileCmd.Builder getFilecommandsBuilder(
            int index) {
      return getFilecommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public test.grpc.grpc.XFileCmdOrBuilder getFilecommandsOrBuilder(
            int index) {
      if (filecommandsBuilder_ == null) {
        return filecommands_.get(index);  } else {
        return filecommandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public java.util.List<? extends test.grpc.grpc.XFileCmdOrBuilder>
    getFilecommandsOrBuilderList() {
      if (filecommandsBuilder_ != null) {
        return filecommandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(filecommands_);
      }
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public test.grpc.grpc.XFileCmd.Builder addFilecommandsBuilder() {
      return getFilecommandsFieldBuilder().addBuilder(
              test.grpc.grpc.XFileCmd.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public test.grpc.grpc.XFileCmd.Builder addFilecommandsBuilder(
            int index) {
      return getFilecommandsFieldBuilder().addBuilder(
              index, test.grpc.grpc.XFileCmd.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc_package.XFileCmd filecommands = 103;</code>
     */
    public java.util.List<test.grpc.grpc.XFileCmd.Builder>
    getFilecommandsBuilderList() {
      return getFilecommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            test.grpc.grpc.XFileCmd, test.grpc.grpc.XFileCmd.Builder, test.grpc.grpc.XFileCmdOrBuilder>
    getFilecommandsFieldBuilder() {
      if (filecommandsBuilder_ == null) {
        filecommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                test.grpc.grpc.XFileCmd, test.grpc.grpc.XFileCmd.Builder, test.grpc.grpc.XFileCmdOrBuilder>(
                filecommands_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        filecommands_ = null;
      }
      return filecommandsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc_package.XRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc_package.XRequest)
  private static final test.grpc.grpc.XRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new test.grpc.grpc.XRequest();
  }

  public static test.grpc.grpc.XRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<XRequest>
          PARSER = new com.google.protobuf.AbstractParser<XRequest>() {
    @java.lang.Override
    public XRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new XRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<XRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<XRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public test.grpc.grpc.XRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

