// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto

package test.grpc.grpc;

public interface XResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc_package.XResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errorno = 1;</code>
   * @return The errorno.
   */
  java.lang.String getErrorno();
  /**
   * <code>string errorno = 1;</code>
   * @return The bytes for errorno.
   */
  com.google.protobuf.ByteString
      getErrornoBytes();

  /**
   * <code>string errmsg = 2;</code>
   * @return The errmsg.
   */
  java.lang.String getErrmsg();
  /**
   * <code>string errmsg = 2;</code>
   * @return The bytes for errmsg.
   */
  com.google.protobuf.ByteString
      getErrmsgBytes();
}
