// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XAccessGrpc.proto

package test.grpc.grpc;

/**
 * Protobuf type {@code rpc_package.XRoute}
 */
public final class XRoute extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc_package.XRoute)
    XRouteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use XRoute.newBuilder() to construct.
  private XRoute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private XRoute() {
    instchain_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new XRoute();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private XRoute(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              instchain_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            instchain_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              instchain_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              instchain_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 16: {

            timeout_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        instchain_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRoute_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRoute_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            test.grpc.grpc.XRoute.class, test.grpc.grpc.XRoute.Builder.class);
  }

  public static final int INSTCHAIN_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList instchain_;
  /**
   * <code>repeated int32 instchain = 1;</code>
   * @return A list containing the instchain.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getInstchainList() {
    return instchain_;
  }
  /**
   * <code>repeated int32 instchain = 1;</code>
   * @return The count of instchain.
   */
  public int getInstchainCount() {
    return instchain_.size();
  }
  /**
   * <code>repeated int32 instchain = 1;</code>
   * @param index The index of the element to return.
   * @return The instchain at the given index.
   */
  public int getInstchain(int index) {
    return instchain_.getInt(index);
  }
  private int instchainMemoizedSerializedSize = -1;

  public static final int TIMEOUT_FIELD_NUMBER = 2;
  private int timeout_;
  /**
   * <code>int32 timeout = 2;</code>
   * @return The timeout.
   */
  @java.lang.Override
  public int getTimeout() {
    return timeout_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getInstchainList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(instchainMemoizedSerializedSize);
    }
    for (int i = 0; i < instchain_.size(); i++) {
      output.writeInt32NoTag(instchain_.getInt(i));
    }
    if (timeout_ != 0) {
      output.writeInt32(2, timeout_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < instchain_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(instchain_.getInt(i));
      }
      size += dataSize;
      if (!getInstchainList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      instchainMemoizedSerializedSize = dataSize;
    }
    if (timeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeout_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof test.grpc.grpc.XRoute)) {
      return super.equals(obj);
    }
    test.grpc.grpc.XRoute other = (test.grpc.grpc.XRoute) obj;

    if (!getInstchainList()
        .equals(other.getInstchainList())) return false;
    if (getTimeout()
        != other.getTimeout()) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInstchainCount() > 0) {
      hash = (37 * hash) + INSTCHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getInstchainList().hashCode();
    }
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static test.grpc.grpc.XRoute parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.grpc.grpc.XRoute parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.grpc.grpc.XRoute parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.grpc.grpc.XRoute parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.grpc.grpc.XRoute parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.grpc.grpc.XRoute parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.grpc.grpc.XRoute parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test.grpc.grpc.XRoute parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static test.grpc.grpc.XRoute parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static test.grpc.grpc.XRoute parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static test.grpc.grpc.XRoute parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test.grpc.grpc.XRoute parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(test.grpc.grpc.XRoute prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc_package.XRoute}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc_package.XRoute)
      test.grpc.grpc.XRouteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRoute_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRoute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.grpc.grpc.XRoute.class, test.grpc.grpc.XRoute.Builder.class);
    }

    // Construct using test.grpc.grpc.XRoute.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      instchain_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      timeout_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return test.grpc.grpc.XAccessGrpc.internal_static_rpc_package_XRoute_descriptor;
    }

    @java.lang.Override
    public test.grpc.grpc.XRoute getDefaultInstanceForType() {
      return test.grpc.grpc.XRoute.getDefaultInstance();
    }

    @java.lang.Override
    public test.grpc.grpc.XRoute build() {
      test.grpc.grpc.XRoute result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public test.grpc.grpc.XRoute buildPartial() {
      test.grpc.grpc.XRoute result = new test.grpc.grpc.XRoute(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        instchain_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.instchain_ = instchain_;
      result.timeout_ = timeout_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof test.grpc.grpc.XRoute) {
        return mergeFrom((test.grpc.grpc.XRoute)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(test.grpc.grpc.XRoute other) {
      if (other == test.grpc.grpc.XRoute.getDefaultInstance()) return this;
      if (!other.instchain_.isEmpty()) {
        if (instchain_.isEmpty()) {
          instchain_ = other.instchain_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureInstchainIsMutable();
          instchain_.addAll(other.instchain_);
        }
        onChanged();
      }
      if (other.getTimeout() != 0) {
        setTimeout(other.getTimeout());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      test.grpc.grpc.XRoute parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (test.grpc.grpc.XRoute) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList instchain_ = emptyIntList();
    private void ensureInstchainIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        instchain_ = mutableCopy(instchain_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 instchain = 1;</code>
     * @return A list containing the instchain.
     */
    public java.util.List<java.lang.Integer>
        getInstchainList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(instchain_) : instchain_;
    }
    /**
     * <code>repeated int32 instchain = 1;</code>
     * @return The count of instchain.
     */
    public int getInstchainCount() {
      return instchain_.size();
    }
    /**
     * <code>repeated int32 instchain = 1;</code>
     * @param index The index of the element to return.
     * @return The instchain at the given index.
     */
    public int getInstchain(int index) {
      return instchain_.getInt(index);
    }
    /**
     * <code>repeated int32 instchain = 1;</code>
     * @param index The index to set the value at.
     * @param value The instchain to set.
     * @return This builder for chaining.
     */
    public Builder setInstchain(
        int index, int value) {
      ensureInstchainIsMutable();
      instchain_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 instchain = 1;</code>
     * @param value The instchain to add.
     * @return This builder for chaining.
     */
    public Builder addInstchain(int value) {
      ensureInstchainIsMutable();
      instchain_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 instchain = 1;</code>
     * @param values The instchain to add.
     * @return This builder for chaining.
     */
    public Builder addAllInstchain(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureInstchainIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, instchain_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 instchain = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstchain() {
      instchain_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int timeout_ ;
    /**
     * <code>int32 timeout = 2;</code>
     * @return The timeout.
     */
    @java.lang.Override
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <code>int32 timeout = 2;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(int value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeout = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {
      
      timeout_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc_package.XRoute)
  }

  // @@protoc_insertion_point(class_scope:rpc_package.XRoute)
  private static final test.grpc.grpc.XRoute DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new test.grpc.grpc.XRoute();
  }

  public static test.grpc.grpc.XRoute getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<XRoute>
      PARSER = new com.google.protobuf.AbstractParser<XRoute>() {
    @java.lang.Override
    public XRoute parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new XRoute(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<XRoute> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<XRoute> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public test.grpc.grpc.XRoute getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

