# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*-mapper.xml
  type-aliases-package: top.niandui.model
  configuration:
    # 开启 将下划线映射到驼峰大小写
    map-underscore-to-camel-case: true
    # 延迟加载：开关
    #lazy-loading-enabled: true
    # 积极加载：true，调用对象的任何属性(不论是否为延迟加载对象的属性)都会加载该对象的所有属性、false，消极加载，按需加载(只有调用延迟加载对象的属性时才会加载)
    #aggressive-lazy-loading: true
    # 一级(本地)缓存范围：session(同一个会话，开启事务),statement(应该是出了方法即失效)
    #local-cache-scope: statement

# pageHelper配置
pagehelper:
  params: count=countSql
  helper-dialect: postgresql #指定分页插件使用哪种方言
  reasonable: 'true' #分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
  support-methods-arguments: 'true'